# environment.yml
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
platforms:
  - linux-64
  - linux-aarch64 # aka arm64, use for Docker on Apple Silicon
  - osx-64
  - osx-arm64 # For Apple Silicon, e.g. M1/M2
  - win-64
  # TODO: Add win-arm64 when available
